- name: Apaga arquivo de configuração original do prometheus
  become: true
  command: rm /etc/prometheus/prometheus.yml -f 

- name: Copia arquivo de configuração customizado do prometheus
  template:
    src: prometheus.yml
    dest: /etc/prometheus


- name: restart do prometheus para aplicar as alterações de host
  become: true
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    
- name: restart do grafana para aplicar as alterações de host
  become: true
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes
